package com.google.android.gms.internal.play_billing;

import com.google.android.gms.fido.u2f.api.common.RegisterRequest;

/* loaded from: classes4.dex */
public final class zzih {
    private static final zzfa zza = new zzif();

    public static int zza(int i11) {
        switch (i11) {
            case 0:
                return 1;
            case 1:
                return 2;
            case 2:
                return 3;
            case 3:
                return 4;
            case 4:
                return 5;
            case 5:
                return 6;
            case 6:
                return 7;
            case 7:
                return 8;
            case 8:
                return 9;
            case 9:
                return 10;
            case 10:
                return 11;
            case 11:
                return 12;
            case 12:
                return 13;
            case 13:
                return 14;
            case 14:
                return 15;
            case 15:
                return 16;
            case 16:
                return 17;
            case 17:
                return 18;
            case 18:
                return 19;
            case 19:
                return 20;
            case 20:
                return 21;
            case 21:
                return 22;
            case 22:
                return 23;
            case 23:
                return 24;
            case 24:
                return 25;
            case 25:
                return 26;
            case 26:
                return 27;
            case 27:
                return 28;
            case 28:
                return 29;
            case NOTIFICATION_REDIRECT_VALUE:
                return 30;
            case 30:
                return 31;
            case TEMPLATE_HTML_SIZE_VALUE:
                return 32;
            case 32:
                return 33;
            case 33:
                return 34;
            case 34:
                return 35;
            case 35:
                return 36;
            case 36:
                return 37;
            case 37:
                return 38;
            case 38:
                return 39;
            case 39:
                return 40;
            case 40:
                return 41;
            case 41:
                return 42;
            case 42:
                return 43;
            case 43:
                return 44;
            case 44:
                return 45;
            case 45:
                return 46;
            case 46:
                return 47;
            case 47:
                return 48;
            case AD_SHOW_TO_VALIDATION_DURATION_MS_VALUE:
                return 49;
            case AD_VALIDATION_TO_PRESENT_DURATION_MS_VALUE:
                return 50;
            case 50:
                return 51;
            case AD_REWARD_USER_VALUE:
                return 52;
            case AD_REQUIRED_DOWNLOAD_DURATION_MS_VALUE:
                return 53;
            case AD_OPTIONAL_DOWNLOAD_DURATION_MS_VALUE:
                return 54;
            case AD_BACKGROUND_BEFORE_IMPRESSION_VALUE:
                return 55;
            case AD_CLOSED_BEFORE_IMPRESSION_VALUE:
                return 56;
            case AD_VISIBILITY_VALUE:
                return 57;
            case 57:
                return 58;
            case INIT_TO_FAIL_CALLBACK_DURATION_MS_VALUE:
                return 59;
            case 59:
                return 60;
            case 60:
                return 61;
            case 61:
                return 62;
            case 62:
                return 63;
            case 63:
                return 64;
            case 64:
                return 65;
            case RegisterRequest.U2F_V1_CHALLENGE_BYTE_LENGTH /* 65 */:
                return 66;
            case 66:
                return 67;
            case 67:
                return 68;
            case 68:
                return 69;
            case 69:
                return 70;
            case 70:
                return 71;
            case 71:
                return 72;
            case 72:
                return 73;
            case 73:
                return 74;
            case 74:
                return 75;
            case 75:
                return 76;
            case 76:
                return 77;
            case 77:
                return 78;
            case 78:
                return 79;
            case 79:
                return 80;
            default:
                return 0;
        }
    }
}
