package com.bytedance.sdk.openadsdk.sef;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.Drawable;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import com.bytedance.sdk.component.utils.ib;
import com.bytedance.sdk.openadsdk.utils.FPG;

/* loaded from: classes3.dex */
public class Fmk extends com.bytedance.sdk.openadsdk.core.HiB.Jcg {
    public Fmk(Context context) {
        this(context, null);
    }

    public Fmk(Context context, AttributeSet attributeSet) {
        this(context, attributeSet, 0);
    }

    public Fmk(Context context, AttributeSet attributeSet, int i11) {
        super(context, attributeSet, i11);
        Sj(context);
    }

    private void Sj(Context context) {
        setId(520093726);
        setBackgroundColor(-1);
        com.bytedance.sdk.openadsdk.core.HiB.Jcg jcg = new com.bytedance.sdk.openadsdk.core.HiB.Jcg(context);
        jcg.setId(com.bytedance.sdk.openadsdk.utils.Zq.GMp);
        jcg.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        jcg.setBackgroundColor(0);
        jcg.setGravity(17);
        addView(jcg);
        View ejP = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        ejP.setId(com.bytedance.sdk.openadsdk.utils.Zq.hzV);
        ejP.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        jcg.addView(ejP);
        com.bytedance.sdk.openadsdk.core.HiB.vS vSVar = new com.bytedance.sdk.openadsdk.core.HiB.vS(context);
        vSVar.setId(com.bytedance.sdk.openadsdk.utils.Zq.TX);
        int sP = FPG.sP(context, 60.0f);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(sP, sP);
        layoutParams.addRule(13);
        vSVar.setLayoutParams(layoutParams);
        vSVar.setIndeterminateDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_video_loading_progress_bar"));
        jcg.addView(vSVar);
        com.bytedance.sdk.openadsdk.core.HiB.HiB hiB = new com.bytedance.sdk.openadsdk.core.HiB.HiB(context);
        hiB.setId(com.bytedance.sdk.openadsdk.utils.Zq.Grp);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams2.addRule(13);
        hiB.setLayoutParams(layoutParams2);
        hiB.setGravity(1);
        hiB.setOrientation(1);
        hiB.setVisibility(8);
        jcg.addView(hiB);
        com.bytedance.sdk.openadsdk.core.HiB.EjP ejP2 = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        ejP2.setId(com.bytedance.sdk.openadsdk.utils.Zq.tX);
        ejP2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        ejP2.setImageDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_refreshing_video_textpage"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER;
        ejP2.setScaleType(scaleType);
        hiB.addView(ejP2);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq2 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq2.setId(com.bytedance.sdk.openadsdk.utils.Zq.Aw);
        dq2.setLayoutParams(new LinearLayout.LayoutParams(-2, -2));
        dq2.setText(ib.Sj(context, "tt_video_retry_des_txt"));
        dq2.setTextColor(Color.parseColor("#999999"));
        hiB.addView(dq2);
        com.bytedance.sdk.openadsdk.core.HiB.EjP ejP3 = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        ejP3.setId(com.bytedance.sdk.openadsdk.utils.Zq.f21219vb);
        RelativeLayout.LayoutParams layoutParams3 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams3.addRule(13);
        ejP3.setLayoutParams(layoutParams3);
        ejP3.setScaleType(scaleType);
        ejP3.setImageDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_play_movebar_textpage"));
        ejP3.setVisibility(8);
        addView(ejP3);
        com.bytedance.sdk.openadsdk.core.HiB.EjP ejP4 = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        ejP4.setId(com.bytedance.sdk.openadsdk.utils.Zq.Ov);
        int sP2 = FPG.sP(context, 30.0f);
        RelativeLayout.LayoutParams layoutParams4 = new RelativeLayout.LayoutParams(sP2, sP2);
        layoutParams4.addRule(21);
        layoutParams4.addRule(11);
        int sP3 = FPG.sP(context, 7.0f);
        layoutParams4.setMarginEnd(sP3);
        layoutParams4.rightMargin = sP3;
        layoutParams4.topMargin = sP3;
        ejP4.setLayoutParams(layoutParams4);
        ejP4.setBackground(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_detail_video_btn_bg"));
        ejP4.setScaleType(scaleType);
        ejP4.setImageDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_close_move_detail"));
        addView(ejP4);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq3 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq3.setId(com.bytedance.sdk.openadsdk.utils.Zq.tPD);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(9);
        layoutParams5.addRule(20);
        layoutParams5.addRule(10);
        dq3.setLayoutParams(layoutParams5);
        dq3.setBackground(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_video_black_desc_gradient"));
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        dq3.setEllipsize(truncateAt);
        dq3.setMaxLines(2);
        int sP4 = FPG.sP(context, 15.0f);
        dq3.setPadding(sP4, FPG.sP(context, 14.0f), sP4, 0);
        dq3.setSingleLine(false);
        dq3.setTextColor(-1);
        dq3.setTextSize(2, 17.0f);
        dq3.setVisibility(8);
        addView(dq3);
        com.bytedance.sdk.openadsdk.core.HiB.Jcg jcg2 = new com.bytedance.sdk.openadsdk.core.HiB.Jcg(context);
        jcg2.setId(com.bytedance.sdk.openadsdk.utils.Zq.WxP);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams6.addRule(10);
        jcg2.setLayoutParams(layoutParams6);
        jcg2.setBackground(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_video_black_desc_gradient"));
        jcg2.setGravity(16);
        jcg2.setVisibility(8);
        addView(jcg2);
        com.bytedance.sdk.openadsdk.core.HiB.EjP ejP5 = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        int i11 = com.bytedance.sdk.openadsdk.utils.Zq.dU;
        ejP5.setId(i11);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams7.addRule(15);
        int sP5 = FPG.sP(context, 12.0f);
        layoutParams7.leftMargin = sP5;
        layoutParams7.setMarginStart(sP5);
        ejP5.setLayoutParams(layoutParams7);
        ejP5.setScaleType(scaleType);
        ejP5.setImageDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_leftbackbutton_titlebar_photo_preview"));
        jcg2.addView(ejP5);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq4 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq4.setId(com.bytedance.sdk.openadsdk.utils.Zq.DPc);
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-2, -1);
        layoutParams8.addRule(15);
        int sP6 = FPG.sP(context, 16.0f);
        layoutParams8.leftMargin = sP6;
        layoutParams8.rightMargin = sP;
        layoutParams8.setMarginStart(sP6);
        layoutParams8.setMarginEnd(sP);
        layoutParams8.addRule(17, i11);
        int i12 = com.bytedance.sdk.openadsdk.utils.Zq.xzt;
        layoutParams8.addRule(0, i12);
        layoutParams8.addRule(1, i11);
        layoutParams8.addRule(16, i12);
        dq4.setLayoutParams(layoutParams8);
        dq4.setEllipsize(truncateAt);
        dq4.setGravity(16);
        dq4.setMaxLines(1);
        dq4.setSingleLine(true);
        dq4.setTextColor(-1);
        dq4.setTextSize(2, 17.0f);
        jcg2.addView(dq4);
        com.bytedance.sdk.openadsdk.core.HiB.HiB hiB2 = new com.bytedance.sdk.openadsdk.core.HiB.HiB(context);
        hiB2.setId(i12);
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams9.addRule(21);
        layoutParams9.addRule(11);
        int sP7 = FPG.sP(context, 14.0f);
        layoutParams9.rightMargin = sP7;
        layoutParams9.setMarginEnd(sP7);
        hiB2.setLayoutParams(layoutParams9);
        hiB2.setGravity(16);
        hiB2.setOrientation(1);
        jcg2.addView(hiB2);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq5 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq5.setId(com.bytedance.sdk.openadsdk.utils.Zq.hif);
        LinearLayout.LayoutParams layoutParams10 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams10.gravity = 1;
        dq5.setLayoutParams(layoutParams10);
        dq5.setGravity(16);
        dq5.setMaxLines(1);
        dq5.setSingleLine(true);
        dq5.setTextColor(-1);
        dq5.setTextSize(2, 12.0f);
        hiB2.addView(dq5);
        com.bytedance.sdk.openadsdk.core.HiB.HiB hiB3 = new com.bytedance.sdk.openadsdk.core.HiB.HiB(context);
        hiB3.setId(com.bytedance.sdk.openadsdk.utils.Zq.Gn);
        RelativeLayout.LayoutParams layoutParams11 = new RelativeLayout.LayoutParams(-2, FPG.sP(context, 40.0f));
        layoutParams11.addRule(12);
        layoutParams11.addRule(21);
        layoutParams11.addRule(11);
        hiB3.setLayoutParams(layoutParams11);
        hiB3.setGravity(16);
        hiB3.setOrientation(0);
        hiB3.setVisibility(8);
        addView(hiB3);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq6 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq6.setId(com.bytedance.sdk.openadsdk.utils.Zq.nou);
        LinearLayout.LayoutParams layoutParams12 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams12.leftMargin = sP6;
        layoutParams12.rightMargin = sP5;
        layoutParams12.setMarginEnd(sP5);
        layoutParams12.setMarginStart(sP6);
        dq6.setLayoutParams(layoutParams12);
        dq6.setText(ib.Sj(context, "tt_00_00"));
        dq6.setTextColor(-1);
        dq6.setTextSize(2, 10.0f);
        hiB3.addView(dq6);
        SeekBar seekBar = new SeekBar(context);
        seekBar.setId(com.bytedance.sdk.openadsdk.utils.Zq.vll);
        LinearLayout.LayoutParams layoutParams13 = new LinearLayout.LayoutParams(0, FPG.sP(context, 5.0f));
        layoutParams13.gravity = 16;
        seekBar.setLayoutParams(layoutParams13);
        seekBar.setMax(100);
        seekBar.setPadding(0, 0, 0, 0);
        seekBar.setProgressDrawable(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_seek_progress"));
        seekBar.setThumb(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_seek_thumb"));
        seekBar.setThumbOffset(0);
        hiB3.addView(seekBar);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq7 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq7.setId(com.bytedance.sdk.openadsdk.utils.Zq.GJs);
        LinearLayout.LayoutParams layoutParams14 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams14.leftMargin = sP5;
        layoutParams14.rightMargin = sP6;
        layoutParams14.setMarginEnd(sP6);
        layoutParams14.setMarginStart(sP5);
        dq7.setLayoutParams(layoutParams14);
        dq7.setText(ib.Sj(context, "tt_00_00"));
        dq7.setTextColor(-1);
        dq7.setTextSize(2, 10.0f);
        hiB3.addView(dq7);
        com.bytedance.sdk.openadsdk.core.HiB.EjP ejP6 = new com.bytedance.sdk.openadsdk.core.HiB.EjP(context);
        ejP6.setId(com.bytedance.sdk.openadsdk.utils.Zq.ron);
        ejP6.setLayoutParams(new LinearLayout.LayoutParams(-2, -1));
        ejP6.setPadding(sP6, 0, sP6, 0);
        ejP6.setScaleType(scaleType);
        ejP6.setVisibility(8);
        ejP6.setImageDrawable(ib.TKC(context, "tt_enlarge_video"));
        hiB3.addView(ejP6);
        View aaVar = new aa(context);
        aaVar.setId(com.bytedance.sdk.openadsdk.utils.Zq.f21217mj);
        aaVar.setLayoutParams(new RelativeLayout.LayoutParams(-1, -1));
        addView(aaVar);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq8 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq8.setId(com.bytedance.sdk.openadsdk.utils.Zq.jjS);
        RelativeLayout.LayoutParams layoutParams15 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams15.leftMargin = sP5;
        layoutParams15.addRule(9);
        layoutParams15.addRule(20);
        dq8.setLayoutParams(layoutParams15);
        dq8.setBackgroundColor(Color.parseColor("#00000000"));
        dq8.setText("close");
        dq8.setMinHeight(FPG.sP(context, 44.0f));
        dq8.setCompoundDrawablesWithIntrinsicBounds(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_shadow_btn_back"), (Drawable) null, (Drawable) null, (Drawable) null);
        addView(dq8);
    }
}
