package com.cloud.hisavana.sdk.common.constant;

import android.text.TextUtils;
import androidx.media3.common.PlaybackException;
import com.cloud.tmc.kernel.minicover.NativeComponentConstants;
import com.hisavana.common.bean.TAdErrorCode;

/* loaded from: classes.dex */
public class TaErrorCode {
    public static final int CCT_LOAD_ABORTED = 8009;
    public static final int CCT_LOAD_EXIT = 8010;
    public static final int CCT_LOAD_FAILED = 8008;
    public static final int CLICK_ERROR_CODE_ADITEM_NULL = 7004;
    public static final int CLICK_ERROR_CODE_CCT_ABTEST_CLOSED = 7020;
    public static final int CLICK_ERROR_CODE_CCT_ABTEST_HIT = 7018;
    public static final int CLICK_ERROR_CODE_CCT_ABTEST_NOT_HIT = 7014;
    public static final int CLICK_ERROR_CODE_CCT_ABTEST_NULL = 7021;
    public static final int CLICK_ERROR_CODE_CCT_ABTEST_PUSH_ALL = 7019;
    public static final int CLICK_ERROR_CODE_CCT_ANDROID_MODEL_BLOCKED = 7011;
    public static final int CLICK_ERROR_CODE_CCT_ANDROID_VERSION_BLOCKED = 7010;
    public static final int CLICK_ERROR_CODE_CCT_BIND_FAILED = 7007;
    public static final int CLICK_ERROR_CODE_CCT_BIND_TIMEOUT = 7006;
    public static final int CLICK_ERROR_CODE_CCT_CONFIG_CLOSED = 7009;
    public static final int CLICK_ERROR_CODE_CCT_LAUNCH_FAILED = 7005;
    public static final int CLICK_ERROR_CODE_CCT_LAUNCH_FAILED_NOT_SESSION = 7013;
    public static final int CLICK_ERROR_CODE_CCT_NOT_INSTALLED = 7008;
    public static final int CLICK_ERROR_CODE_CCT_SPLASH_NOT_ALLOW = 7012;
    public static final int CLICK_ERROR_CODE_CONFIG_CREATIVE_ID_OPEN_DEFAULT = 7016;
    public static final int CLICK_ERROR_CODE_CONFIG_NOT_ENABLE_DEFAULT_BROWSER = 7017;
    public static final int CLICK_ERROR_CODE_CONTEXT_NULL = 7003;
    public static final int CLICK_ERROR_CODE_DEFAULT_BROWSER_LAUNCH_FAILED = 7015;
    public static final int CLICK_ERROR_CODE_FAILED = 7001;
    public static final int CLICK_ERROR_CODE_NOT_GET_DEFAULT_BROWSER_PKG = 7022;
    public static final int CLICK_ERROR_CODE_NOT_HTTP_URL = 7023;
    public static final int CLICK_ERROR_CODE_OPEN_BROWSER_FAILED = 7002;
    public static final int CODE_ADM_SCALE_TAKE_FAILED = 3006;
    public static final int CODE_AD_MATERIAL_DOWNLOAD_ERROR = 5029;
    public static final int CODE_AD_MATERIAL_TAKE_FAILED = 3002;
    public static final int CODE_AD_NO_NETWORK = 5028;
    public static final int CODE_AD_ONLINE_LOW_PRICE = 5031;
    public static final int CODE_AD_ONLINE_REQ_NOT_RETURN = 5026;
    public static final int CODE_AD_ONLY_REQ_DEFAULT = 5027;
    public static final int CODE_AD_TOTAL_REQ_TIMEOUT = 5025;
    public static final int CODE_INTERVAL_NOT_REACHED = 2005;
    public static final int CODE_INVALID_APP_ID_ = 2006;
    public static final int CODE_NETWORK_NOT_CONNECTED = 2004;
    public static final int CODE_NETWORK_REQUEST_TIME_OUT = 2003;
    public static final int CODE_RESPONSE_IS_NULL = 2002;
    public static final int CODE_RESPONSE_PARSING_FAILED = 2001;
    public static final int CODE_SHOW_OUTER_INVALID = 6000;
    public static final int CODE_SPLASH_MATERIAL_LOAD_FAILED = 3001;
    public static final int CODE_STORE_MATERIAL_TAKE_FAILED = 3003;
    public static final int CODE_SUCCESS = 0;
    public static final int CODE_UNINIT = 9001;
    public static final int CODE_UNKNOWN = -1;
    public static final int CODE_ZIP_MATERIAL_DECOMPRESS_FAILED = 3005;
    public static final int CODE_ZIP_MATERIAL_TAKE_FAILED = 3004;
    public static final int ERROR_ONLINE_MATERIAL_NOT_RETURN = 5030;
    public static final int ERROR_ONLINE_TIMEOUT_MATERIAL_NOT_RETURN = 5032;
    public static final int ERROR_TOTAL_TIMEOUT_MATERIAL_NOT_RETURN = 5033;
    public static final int VAST_VIDEO_PLAY_ERROR = 3011;
    public static final int WEBVIEW_ADSDTO_NULL = 8001;
    public static final int WEBVIEW_CREAT_ERROR = 8007;
    public static final int WEBVIEW_INTENT_NULL = 8006;
    public static final int WEBVIEW_ON_DESTORY = 8005;
    public static final int WEBVIEW_URL_DEEPLINK = 8004;
    public static final int WEBVIEW_URL_EMPTY = 8002;
    public static final int WEBVIEW_URL_GP = 8003;
    private final int errorCode;
    private final String errorMessage;
    public static final TaErrorCode ERROR_UNKNOWN = new TaErrorCode(-1, "unknown error");
    public static final TaErrorCode ERROR_SUCCESS = new TaErrorCode(0, NativeComponentConstants.KEY_COMPONENT_RESULT_SUCCESS);
    public static final TaErrorCode ERROR_RESPONSE_PARSING_FAILED = new TaErrorCode(2001, "response parse failed");
    public static final TaErrorCode ERROR_RESPONSE_IS_NULL = new TaErrorCode(2002, "response is null");
    public static final TaErrorCode ERROR_NETWORK_REQUEST_TIME_OUT = new TaErrorCode(2003, "network request timeout");
    public static final TaErrorCode ERROR_NETWORK_NOT_CONNECTED = new TaErrorCode(2004, "network is not connected");
    public static final TaErrorCode ERROR_INVALID_APP_ID = new TaErrorCode(2006, "invalid app id");
    public static final TaErrorCode ERROR_AD_MATERIAL_TAKE_FAILED = new TaErrorCode(3002, "creative url is empty or download failed");
    public static final TaErrorCode ERROR_STORE_MATERIAL_TAKE_FAILED = new TaErrorCode(3003, "store material url is empty or download failed");
    public static final TaErrorCode ERROR_ZIP_MATERIAL_TAKE_FAILED = new TaErrorCode(3004, "material zip load failed");
    public static final TaErrorCode ERROR_ZIP_MATERIAL_DECOMPRESS_FAILED = new TaErrorCode(3005, "material zip decompress failed");
    public static final TaErrorCode ERROR_ADM_SCALE_TAKE_FAILED = new TaErrorCode(3006, "adm scales is not fit");
    public static final int CODE_BITMAP_TAKE_FAILED = 3007;
    public static final TaErrorCode ERROR_BITMAP_TAKE_FAILED = new TaErrorCode(CODE_BITMAP_TAKE_FAILED, "image acquisition failed");
    private static final int NO_MAIN_VIDEO_DATA = 3008;
    public static final TaErrorCode NO_MAIN_VIDEO_DATA_ERROR = new TaErrorCode(NO_MAIN_VIDEO_DATA, "video resource is empty");
    private static final int MAIN_VIDEO_DOWNLOAD_FAIL = 3009;
    public static final TaErrorCode MAIN_VIDEO_DOWNLOAD_FAIL_ERROR = new TaErrorCode(MAIN_VIDEO_DOWNLOAD_FAIL, "video resource is empty");
    private static final int NO_MAIN_IMG_DATA = 3010;
    public static final TaErrorCode NO_MAIN_IMG_DATA_ERROR = new TaErrorCode(NO_MAIN_IMG_DATA, "image resource is null");
    private static final int MATERIAL_TYPE_IS_NOT_VIDEO = 3012;
    public static final TaErrorCode MATERIAL_TYPE_IS_NOT_VIDEO_ERROR = new TaErrorCode(MATERIAL_TYPE_IS_NOT_VIDEO, "material type is not video");
    public static final int CODE_INTERSTITIAL_MISS_ELEMENT = 3013;
    public static final TaErrorCode ERROR_INTERSTITIAL_MISS_ELEMENT = new TaErrorCode(CODE_INTERSTITIAL_MISS_ELEMENT, "Missing necessary elements");
    public static final int CODE_INVALID_TYPE = 3014;
    public static final TaErrorCode ERROR_INVALID_TYPE = new TaErrorCode(CODE_INVALID_TYPE, "Invalid type");
    public static final int CODE_ADM_LOAD_FAILED = 3015;
    public static final TaErrorCode ERROR_ADM_LOAD_FAILED = new TaErrorCode(CODE_ADM_LOAD_FAILED, "Adm load failed");
    public static final int CODE_BITMAP_TOO_LARGE = 3016;
    public static final TaErrorCode ERROR_BITMAP_TOO_LARGE = new TaErrorCode(CODE_BITMAP_TOO_LARGE, "image is too large");
    public static final int CODE_FILE_NO_SUPPORT = 3017;
    public static final TaErrorCode ERROR_FILE_NO_SUPPORT = new TaErrorCode(CODE_FILE_NO_SUPPORT, "file format is not support on this device");
    public static final TaErrorCode ERROR_MATERIAL_DOWNLOAD_LOCAL_BEAN_NULL = new TaErrorCode(3018, "localbean is null");
    public static final TaErrorCode ERROR_MATERIAL_DOWNLOAD_URL_IS_EMPTY = new TaErrorCode(3019, "material download url  is null");
    public static final TaErrorCode ERROR_DOWNLOAD_URL_IS_EMPTY = new TaErrorCode(3020, "download url  is null");
    public static final TaErrorCode ERROR_DOWNLOAD_NO_NETWORK = new TaErrorCode(3021, "download no network");
    public static final TaErrorCode ERROR_ADM_IS_NULL = new TaErrorCode(3022, "adm is null ");
    public static final TaErrorCode ERROR_ADM_URL_IS_EMPTY = new TaErrorCode(3023, "adm url is null");
    public static final TaErrorCode ERROR_DOWNLOAD_MATERIAL_ADS_IS_NULL = new TaErrorCode(3024, "download material ads is null ");
    public static final TaErrorCode ERROR_PRE_CACHE_IMG_URL_IS_EMPTY = new TaErrorCode(3025, "image url is empty");
    public static final TaErrorCode ERROR_MATERIAL_STORE_IMG_URL_IS_EMPTY = new TaErrorCode(3026, "store image url is empty");
    public static final int CODE_AD_SHOW_NOT_IN_INTERVAL = 4009;
    public static final TaErrorCode ERROR_AD_SHOW_NOT_IN_INTERVAL = new TaErrorCode(CODE_AD_SHOW_NOT_IN_INTERVAL, "ad show not in interval");
    public static final int CODE_AD_UNIT_CONFIG_IS_EMPTY = 4100;
    public static final TaErrorCode ERROR_AD_NEW_UNIT_CONFIG_IS_EMPTY = new TaErrorCode(CODE_AD_UNIT_CONFIG_IS_EMPTY, "unable to obtain valid ad code seat id");
    public static final TaErrorCode ERROR_AD_DEFAULT_DATA_IS_NULL = new TaErrorCode(5001, "ad data is null");
    public static final TaErrorCode ERROR_AD_OFFLINE_DATA_IS_NULL = new TaErrorCode(5002, "ad data is null");
    public static final TaErrorCode ERROR_AD_ONLINE_RESPONSE_IS_NULL = new TaErrorCode(PlaybackException.ERROR_CODE_AUDIO_TRACK_OFFLOAD_WRITE_FAILED, "ad data is null");
    public static final TaErrorCode ERROR_AD_ONLINE_ADS_IS_NULL = new TaErrorCode(PlaybackException.ERROR_CODE_AUDIO_TRACK_OFFLOAD_INIT_FAILED, "ad data is null");
    public static final TaErrorCode ERROR_AD_INTERSTITIAL_MATERIAL_IS_NULL = new TaErrorCode(5005, "interstitial material is null");
    public static final TaErrorCode ERROR_AD_SPLASH_MATERIAL_IS_NULL = new TaErrorCode(5006, "splash material is null");
    public static final TaErrorCode ERROR_AD_MATERIAL_DOWNLOAD_IS_NULL = new TaErrorCode(5007, "material download is null");
    public static final TaErrorCode ERROR_AD_NATIVE_MATERIAL_DOWNLOAD_IS_NULL = new TaErrorCode(5008, "native material download is null");
    public static final TaErrorCode ERROR_AD_ONLINE_AD_CREATIVIES_IS_NULL = new TaErrorCode(5009, "online ad creatives is null");
    public static final TaErrorCode ERROR_AD_BIDDING_AD_IS_NULL = new TaErrorCode(5010, "bidding ad is null");
    public static final TaErrorCode ERROR_AD_FETCHED_AD_IS_NULL = new TaErrorCode(5011, "featch ad is null");
    public static final TaErrorCode ERROR_AD_REWARDED_AD_MATERIAL_IS_NULL = new TaErrorCode(5012, "rewarede ad material is null");
    public static final TaErrorCode ERROR_AD_OFFLINE_AD_IS_NULL = new TaErrorCode(5013, "ad data is null");
    public static final TaErrorCode ERROR_AD_ONLINE_PLACEMENT_ID_MISMATCH = new TaErrorCode(5014, "ad slot id does not match");
    public static final TaErrorCode ERROR_AD_OFFLINE_PLACEMENT_ID_MISMATCH = new TaErrorCode(5015, "ad slot id does not match");
    public static final TaErrorCode ERROR_AD_ONLINE_TYPE_MISMATCH = new TaErrorCode(5016, "ad type does not match");
    public static final TaErrorCode ERROR_AD_OFFLINE_TYPE_MISMATCH = new TaErrorCode(5017, "ad type does not match");
    public static final TaErrorCode ERROR_ADS_ONLINE_ARE_FILTERED = new TaErrorCode(5018, "returned ads are filtered");
    public static final TaErrorCode ERROR_ADS_OFFLINE_ARE_FILTERED = new TaErrorCode(5019, "returned ads are filtered");
    public static final TaErrorCode ERROR_TAKE_AD_RESULT_FAILED = new TaErrorCode(5020, "no ads available");
    public static final TaErrorCode ERROR_AD_NEW_IMPRESSION_LIMIT = new TaErrorCode(5021, "ad impression limit");
    public static final TaErrorCode ERROR_AD_CHAIN_IS_NULL = new TaErrorCode(5022, "ad impression limit");
    public static final TaErrorCode ERROR_ONLINE_NEW_REQUEST_TIMEOUT = new TaErrorCode(5023, "online request time out");
    public static final TaErrorCode ERROR_AD_VAST_MATERIAL_DOWNLOAD_IS_NULL = new TaErrorCode(5024, "material download is null");
    public static final TaErrorCode ERROR_SHOW_OUTER_INVALID = new TaErrorCode(6000, "ad data is Invalid");
    public static final TaErrorCode ERROR_SHOW_INNER_INVALID = new TaErrorCode(6001, "ad data is Invalid");
    public static final TaErrorCode ERROR_SHOW_ADBEAN_NULL = new TaErrorCode(6002, "ad data is null");
    public static final TaErrorCode ERROR_SHOW_INTERACTIVE_WEBVIEW_ERROR = new TaErrorCode(6003, "ad container created error");
    public static final TaErrorCode ERROR_SHOW_MATERIAL_STYLE_NULL = new TaErrorCode(6004, "material style is null");
    public static final TaErrorCode ERROR_SHOW_ADMEDIATYPE_INVALID = new TaErrorCode(6005, "adMediaType is invalid type");
    public static final TaErrorCode ERROR_SHOW_VIEWGROUP_NULL = new TaErrorCode(6006, "ad viewgroup is null");
    public static final TaErrorCode ERROR_SHOW_NATIVEOBJ_NULL = new TaErrorCode(6007, "ad native obj is null");
    public static final TaErrorCode ERROR_SHOW_RENDERVIEW_NULL = new TaErrorCode(6008, "ad renderView is null");
    public static final TaErrorCode ERROR_SHOW_ADM_NULL = new TaErrorCode(6009, "ad adm is null");
    public static final TaErrorCode ERROR_SHOW_ADM_WEBVIEW_ERROR = new TaErrorCode(6010, "ad container created error");
    public static final TaErrorCode ERROR_SHOW_ADM_LOAD_MATERIAL_ERROR = new TaErrorCode(6011, "ad load material error");
    public static final TaErrorCode ERROR_SHOW_H5_ADURL_NULL = new TaErrorCode(6012, "ad H5Url error");
    public static final TaErrorCode ERROR_SHOW_BANNER_WEBVIEW_LOAD_ERROR = new TaErrorCode(6013, "ad load error");
    public static final TaErrorCode ERROR_SHOW_SPLASH_VIEW_NULL = new TaErrorCode(6014, "ad splash view error");
    public static final TaErrorCode ERROR_SHOW_INDEXLOCATION_EMPTY = new TaErrorCode(6015, "ad indexlocation empty");
    public static final TaErrorCode ERROR_SHOW_AD_MAINURL_EMPTY = new TaErrorCode(6016, "ad mainurl empty");
    public static final TaErrorCode ERROR_SHOW_AD_INTERACTIVEAD_FILE_NOT_EXIST = new TaErrorCode(6017, "ad interactivead file not exist");
    public static final int CODE_INIT_ERROR = 6018;
    public static final TaErrorCode ERROR_SHOW_INIT_ERROR = new TaErrorCode(CODE_INIT_ERROR, "Not initialized");
    public static final int CODE_SHOW_SNETWORK_NOT_CONNECTED = 6019;
    public static final TaErrorCode ERROR_SHOW_NETWORK_NOT_CONNECTED = new TaErrorCode(CODE_SHOW_SNETWORK_NOT_CONNECTED, "network is not connected");
    public static final TaErrorCode ERROR_SHOW_AD_MATERIAL_STYLE_NOT_MATCH = new TaErrorCode(6021, "material style is not match");
    public static final TaErrorCode ERROR_SHOW_ADM_LOAD_WEB_ERROR = new TaErrorCode(6022, "ad load material error");
    public static final TaErrorCode ERROR_SHOW_ADM_LOAD_WEB_MATERIAL_ERROR = new TaErrorCode(6023, "ad load material error");
    public static final TaErrorCode ERROR_SHOW_LAYOUT_ERROR = new TaErrorCode(6024, "ad layout error");
    public static final int CODE_SHOW_VIDEO_PLAYER_IO_ERROR = 6025;
    public static final TaErrorCode ERROR_SHOW_VIDEO_PLAYER_IO_ERROR = new TaErrorCode(CODE_SHOW_VIDEO_PLAYER_IO_ERROR, "video player io error");
    public static final int CODE_SHOW_VIDEO_PLAYER_DECODE_ERROR = 6026;
    public static final TaErrorCode ERROR_SHOW_VIDEO_PLAYER_DECODE_ERROR = new TaErrorCode(CODE_SHOW_VIDEO_PLAYER_DECODE_ERROR, "video player decode error");
    public static final int CODE_SHOW_VIDEO_PLAYER_DRM_ERROR = 6027;
    public static final TaErrorCode ERROR_SHOW_VIDEO_PLAYER_DRM_ERROR = new TaErrorCode(CODE_SHOW_VIDEO_PLAYER_DRM_ERROR, "video player drm error");
    public static final int CODE_SHOW_VIDEO_PLAYER_UNKNOWN_ERROR = 6028;
    public static final TaErrorCode ERROR_SHOW_VIDEO_PLAYER_UNKNOWN_ERROR = new TaErrorCode(CODE_SHOW_VIDEO_PLAYER_UNKNOWN_ERROR, "video player unknown error");
    public static final int CODE_SHOW_VIDEO_PLAYER_UNAVAILABLE = 6029;
    public static final TaErrorCode ERROR_SHOW_VIDEO_PLAYER_UNAVAILABLE = new TaErrorCode(CODE_SHOW_VIDEO_PLAYER_UNAVAILABLE, "video player unavailable");

    public TaErrorCode(int i11, String str) {
        str = TextUtils.isEmpty(str) ? TAdErrorCode.EMPTY_MSG : str;
        this.errorCode = i11;
        this.errorMessage = str;
    }

    public int getErrorCode() {
        return this.errorCode;
    }

    public String getErrorMessage() {
        return this.errorMessage;
    }

    public String toString() {
        return "TaErrorCode{errorCode=" + this.errorCode + ", errorMessage='" + this.errorMessage + "'}";
    }
}
