package com.bytedance.sdk.openadsdk.component.reward.view;

import android.content.Context;
import android.graphics.Color;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import androidx.core.view.ViewCompat;
import com.bytedance.sdk.component.utils.ib;
import com.bytedance.sdk.openadsdk.common.aa;
import com.bytedance.sdk.openadsdk.core.model.sU;
import com.bytedance.sdk.openadsdk.core.widget.PAGLogoView;
import com.bytedance.sdk.openadsdk.core.widget.uvD;
import com.bytedance.sdk.openadsdk.utils.FPG;
import com.bytedance.sdk.openadsdk.utils.Zq;

/* loaded from: classes3.dex */
public class EjP {
    public static void Sj(FrameLayout frameLayout) {
        Context context = frameLayout.getContext();
        View tkc = new TKC(context);
        tkc.setId(Zq.f21209aa);
        tkc.setVisibility(8);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(-1, -2);
        layoutParams.gravity = 80;
        frameLayout.addView(tkc, layoutParams);
        View hiB = new com.bytedance.sdk.openadsdk.core.HiB.HiB(context);
        hiB.setId(Zq.Fmk);
        hiB.setVisibility(8);
        frameLayout.addView(hiB, new FrameLayout.LayoutParams(-1, -1));
        View vSVar = new com.bytedance.sdk.component.uA.vS(context, true);
        vSVar.setLayerType(2, null);
        vSVar.setVisibility(4);
        vSVar.setId(Zq.sef);
        frameLayout.addView(vSVar, new FrameLayout.LayoutParams(-1, -1));
        View frameLayout2 = new FrameLayout(context);
        frameLayout2.setId(Zq.Zq);
        frameLayout2.setVisibility(4);
        frameLayout.addView(frameLayout2, new FrameLayout.LayoutParams(-1, -1));
        View vSVar2 = new com.bytedance.sdk.component.uA.vS(context, true);
        vSVar2.setVisibility(8);
        vSVar2.setId(Zq.uvD);
        frameLayout.addView(vSVar2, new FrameLayout.LayoutParams(-1, -1));
        frameLayout.addView(new RFEndCardBackUpLayout(context), new FrameLayout.LayoutParams(-1, -1));
    }

    public static void Sj(FrameLayout frameLayout, sU sUVar) {
        Context context = frameLayout.getContext();
        com.bytedance.sdk.openadsdk.core.HiB.Jcg jcg = new com.bytedance.sdk.openadsdk.core.HiB.Jcg(context);
        jcg.setId(Zq.kF);
        jcg.setBackgroundColor(Color.parseColor("#F8F8F8"));
        frameLayout.addView(jcg, new FrameLayout.LayoutParams(-1, -1));
        View aaVar = new aa(context);
        aaVar.setId(Zq.uP);
        jcg.addView(aaVar, new RelativeLayout.LayoutParams(-1, -1));
        com.bytedance.sdk.openadsdk.core.HiB.HiB hiB = new com.bytedance.sdk.openadsdk.core.HiB.HiB(context);
        hiB.setId(Zq.wE);
        hiB.setOrientation(1);
        hiB.setVisibility(8);
        hiB.setGravity(1);
        hiB.setId(Zq.FPG);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams.addRule(13);
        jcg.addView(hiB, layoutParams);
        uvD uvd = new uvD(context);
        uvd.setId(Zq.LqL);
        hiB.addView(uvd, new LinearLayout.LayoutParams(FPG.sP(context, 80.0f), FPG.sP(context, 80.0f)));
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq2 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq2.setId(Zq.Yf);
        dq2.setTextColor(Color.parseColor("#161823"));
        dq2.setTextSize(2, 24.0f);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.topMargin = FPG.sP(context, 12.0f);
        hiB.addView(dq2, layoutParams2);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq3 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq3.setId(Zq.LD);
        dq3.setGravity(17);
        dq3.setTextColor(Color.parseColor("#80161823"));
        dq3.setTextSize(2, 16.0f);
        dq3.setTextAlignment(4);
        LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(-2, -2);
        int sP = FPG.sP(context, 60.0f);
        layoutParams3.leftMargin = sP;
        layoutParams3.rightMargin = sP;
        layoutParams3.setMarginStart(sP);
        layoutParams3.setMarginEnd(layoutParams3.rightMargin);
        layoutParams3.topMargin = FPG.sP(context, 8.0f);
        hiB.addView(dq3, layoutParams3);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq4 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq4.setId(Zq.fF);
        dq4.setGravity(17);
        dq4.setTextColor(-1);
        dq4.setText(ib.Sj(context, "tt_video_mobile_go_detail"));
        dq4.setBackground(com.bytedance.sdk.openadsdk.utils.TEQ.Sj(context, "tt_reward_video_download_btn_bg"));
        LinearLayout.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(FPG.sP(context, 255.0f), FPG.sP(context, 44.0f));
        layoutParams4.topMargin = FPG.sP(context, 32.0f);
        hiB.addView(dq4, layoutParams4);
        com.bytedance.sdk.openadsdk.core.HiB.Dq dq5 = new com.bytedance.sdk.openadsdk.core.HiB.Dq(context);
        dq5.setId(Zq.ley);
        dq5.setGravity(17);
        dq5.setTextColor(ViewCompat.MEASURED_STATE_MASK);
        dq5.setText("Sorry,this AD fails to load...");
        dq5.setVisibility(8);
        dq5.setGravity(1);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-1, -2);
        layoutParams5.addRule(13);
        jcg.addView(dq5, layoutParams5);
        View createPAGLogoViewByMaterial = PAGLogoView.createPAGLogoViewByMaterial(context, sUVar);
        createPAGLogoViewByMaterial.setId(Zq.JcM);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(-2, FPG.sP(context, 14.0f));
        layoutParams6.addRule(12);
        int sP2 = FPG.sP(context, 16.0f);
        layoutParams6.leftMargin = sP2;
        layoutParams6.setMarginStart(sP2);
        layoutParams6.bottomMargin = FPG.sP(context, 20.0f);
        jcg.addView(createPAGLogoViewByMaterial, layoutParams6);
    }
}
